name: Generate blog
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  generate_cafe_hopper_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Current date and time
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

    - name: Commit changes
      run: |
        touch public/new-blog2.html

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: Update public directory
        branch: create-pull-request/patch-${{ steps.datetime.outputs.datetime }}
