name: Generate blog
on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 * * *"
jobs:
  generate_cafe_hopper_blog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Git
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"

    - name: Commit changes
      run: |
        touch public/new-blog.html

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        title: Update public directory
